<?php

namespace Vuba\AuthN\UserStorage;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityManagerInterface;

require_once __DIR__.'/../../config/bootstrap.php';

class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function load($uid, EntityManagerInterface $em){
        $userRepo = $em->getRepository('UserObject');
        return $userRepo->find($uid);
    }

    public function save(\Vuba\AuthN\User\UserObject $user, EntityManagerInterface $em){
        $em->getRepository('UserObject')
            ->persit($user);
        $em->flush();
    }

    public function listUser(EntityManagerInterface $em){
        $users  = $em->getRepository('UserObject')
            ->findAll();
        return $users;
    }
}
